#!/usr/bin/env python3
"""
SDTM DDL Generator
==================
Generates CREATE TABLE SQL statements for all 8 SDTM domains.
Reads variable definitions from domain skill markdown files via domain_parser.py.

Usage:
  python sdtm_ddl_generator.py --dialect duckdb --output sdtm_schema.sql
  python sdtm_ddl_generator.py --dialect postgres --output sdtm_schema.sql
  python sdtm_ddl_generator.py --dialect sqlite --output_dir ./ddl/
"""

import json
import sys
import os
from typing import Dict, List, Optional

# ── Import shared parser (single source of truth) ──────────────────────────
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from domain_parser import DomainParser, DomainDef

# ═══════════════════════════════════════════════════════════════════════════════
# SQL Type Mapping
# ═══════════════════════════════════════════════════════════════════════════════

TYPE_MAPPING = {
    "sqlite":   {"text": "TEXT", "integer": "INTEGER", "float": "REAL", "datetime": "TEXT"},
    "postgres": {"text": "VARCHAR", "integer": "INTEGER", "float": "DOUBLE PRECISION", "datetime": "TIMESTAMP"},
    "duckdb":   {"text": "VARCHAR", "integer": "INTEGER", "float": "DOUBLE", "datetime": "TIMESTAMP"},
}

INDEX_PATTERNS = {
    "AE": ["USUBJID", "AEDECOD", "AEBODSYS"],
    "CM": ["USUBJID"],
    "VS": ["USUBJID", "VSTESTCD"],
    "LB": ["USUBJID", "LBTESTCD"],
    "EX": ["USUBJID"],
    "DS": ["USUBJID"],
    "MH": ["USUBJID"],
}


def sql_type(parser_type: str, dialect: str) -> str:
    """Map domain parser type to SQL type."""
    return TYPE_MAPPING.get(dialect, TYPE_MAPPING["duckdb"]).get(parser_type, "TEXT")


def generate_ddl(dd: DomainDef, dialect: str = "duckdb") -> str:
    """Generate CREATE TABLE DDL for a domain using definitions from domain_parser."""
    lines = [
        f"-- Domain: {dd.name} — {dd.description[:80]}",
        f"-- Observation Class: {dd.observation_class}",
        f"-- Source: {os.path.basename(dd.source_file)}",
        f"-- Dialect: {dialect}",
        "",
        f"CREATE TABLE IF NOT EXISTS {dd.name.lower()} (",
    ]

    col_defs = []
    for var in dd.variables:
        col_type = sql_type(var.type, dialect)
        nullable = "NOT NULL" if var.required else ""
        comment = f"  -- {var.label}"
        if var.codelist:
            comment += f" [CT: {var.codelist}]"
        col_defs.append(f"    {var.name} {col_type} {nullable},{comment}")

    # Primary key
    pk_cols = ", ".join(dd.primary_key)
    col_defs.append(f"    PRIMARY KEY ({pk_cols})")

    lines.extend(col_defs)
    lines.append(");")
    lines.append("")

    # Foreign key (non-DM domains)
    if dd.name != "DM":
        lines.append(f"-- FK: {dd.name}.USUBJID → DM.USUBJID")
        lines.append(f"ALTER TABLE {dd.name.lower()} ADD CONSTRAINT fk_{dd.name.lower()}_dm")
        lines.append(f"    FOREIGN KEY (USUBJID) REFERENCES dm(USUBJID);")
        lines.append("")

    # Indexes
    indexes = INDEX_PATTERNS.get(dd.name, ["USUBJID"])
    lines.append("-- Indexes")
    for col in indexes:
        idx_name = f"idx_{dd.name.lower()}_{col.lower()}"
        lines.append(f"CREATE INDEX IF NOT EXISTS {idx_name} ON {dd.name.lower()}({col});")
    lines.append("")

    return "\n".join(lines)


def generate_all_ddl(parser: DomainParser, dialect: str = "duckdb") -> str:
    """Generate DDL for all 8 domains in dependency order."""
    parts = [
        "-- SDTM IG 3.4 Database Schema",
        "-- Generated by sdtm_ddl_generator.py (source: domain skill files)",
        f"-- Dialect: {dialect}",
        "",
        "BEGIN TRANSACTION;",
        "",
    ]
    for domain_name in parser.get_all_domains():
        dd = parser.get_domain(domain_name)
        parts.append(generate_ddl(dd, dialect))
    parts.append("COMMIT;")
    parts.append(f"\n-- Tables: {len(parser.get_all_domains())} | Generated from domains/*.md via domain_parser")
    return "\n".join(parts)


def generate_column_metadata(parser: DomainParser) -> Dict:
    """Generate JSON metadata for define.xml from domain parser."""
    meta = {"domains": {}}
    for domain_name in parser.get_all_domains():
        dd = parser.get_domain(domain_name)
        domain_meta = {
            "domain": dd.name,
            "description": dd.description[:200],
            "observation_class": dd.observation_class,
            "variables": [],
        }
        for var in dd.variables:
            domain_meta["variables"].append({
                "name": var.name, "label": var.label,
                "type": var.type, "length": var.length,
                "required": var.required, "codelist": var.codelist,
                "origin": var.origin,
            })
        meta["domains"][dd.name] = domain_meta
    return meta


# ── CLI ─────────────────────────────────────────────────────────────────────

def main():
    import argparse
    parser_arg = argparse.ArgumentParser(description="SDTM DDL Generator (reads domain skill files)")
    parser_arg.add_argument("--project-root", default=".", help="TrialSim project root directory")
    parser_arg.add_argument("--dialect", choices=["sqlite", "postgres", "duckdb"], default="duckdb")
    parser_arg.add_argument("--output", "-o", help="Output SQL file")
    parser_arg.add_argument("--output-dir", help="Output directory for per-domain DDL files")
    parser_arg.add_argument("--metadata", help="Output column metadata JSON (for define.xml)")
    parser_arg.add_argument("--domain", help="Single domain only")
    args = parser_arg.parse_args()

    # Load domain definitions from markdown files
    project_root = os.path.abspath(args.project_root)
    p = DomainParser(project_root)

    if args.domain:
        dd = p.get_domain(args.domain.upper())
        ddl = generate_ddl(dd, args.dialect)
        if args.output:
            with open(args.output, "w") as f: f.write(ddl)
        else:
            print(ddl)
    else:
        p.load_all()
        ddl = generate_all_ddl(p, args.dialect)
        if args.output:
            with open(args.output, "w") as f: f.write(ddl)
            print(f"数据库模式（{len(p.get_all_domains())} 张表） → {args.output}")
        elif args.output_dir:
            os.makedirs(args.output_dir, exist_ok=True)
            for domain_name in p.get_all_domains():
                dd = p.get_domain(domain_name)
                with open(os.path.join(args.output_dir, f"{domain_name.lower()}.sql"), "w") as f:
                    f.write(generate_ddl(dd, args.dialect))
            print(f"按域生成DDL → {args.output_dir}")
        else:
            print(ddl)

    if args.metadata:
        meta = generate_column_metadata(p)
        with open(args.metadata, "w") as f:
            json.dump(meta, f, indent=2)
        print(f"元数据 → {args.metadata}")


if __name__ == "__main__":
    main()
